# Merge Data SST Pasuruan (2016-2025)

Notebook ini menggabungkan seluruh file CSV tahunan SST (Sea Surface Temperature) untuk wilayah Pasuruan (2016-2025) menjadi **satu file CSV** utuh.

**Tahapan:**
1. Import library yang dibutuhkan
2. Cari semua file `.csv` di folder data
3. Baca & gabungkan (merge) seluruh file menjadi satu DataFrame
4. Bersihkan & rapikan data
5. Export ke CSV

In [1]:
# 1. Import library
import os
import glob
import pandas as pd

In [2]:
# 2. Cari semua file .csv di folder data
data_folder = "data"  # folder tempat semua file csv per tahun disimpan
file_list = sorted(glob.glob(os.path.join(data_folder, "sst_pasuruan_*.csv")))

print(f"Jumlah file ditemukan: {len(file_list)}")
file_list

Jumlah file ditemukan: 10

['data/sst_pasuruan_2016.csv',
 'data/sst_pasuruan_2017.csv',
 'data/sst_pasuruan_2018.csv',
 'data/sst_pasuruan_2019.csv',
 'data/sst_pasuruan_2020.csv',
 'data/sst_pasuruan_2021.csv',
 'data/sst_pasuruan_2022.csv',
 'data/sst_pasuruan_2023.csv',
 'data/sst_pasuruan_2024.csv',
 'data/sst_pasuruan_2025.csv']

## 3. Gabungkan seluruh file CSV

Setiap file memiliki baris kedua berisi satuan (unit), bukan data, sehingga baris tersebut perlu dilewati (`skiprows=[1]`) saat dibaca.

In [3]:
# 3. Baca dan gabungkan semua file csv menjadi satu DataFrame
df_list = []
for f in file_list:
    temp = pd.read_csv(f, skiprows=[1])  # baris ke-2 berisi satuan, dilewati
    df_list.append(temp)

df = pd.concat(df_list, ignore_index=True)
print(f"Jumlah baris setelah digabung: {len(df)}")
df.head()

Jumlah baris setelah digabung: 3647

                   time  zlev  latitude  longitude    sst
0  2016-01-01T12:00:00Z   0.0    -6.875    113.125  30.23
1  2016-01-02T12:00:00Z   0.0    -6.875    113.125  30.01
2  2016-01-03T12:00:00Z   0.0    -6.875    113.125  30.02
3  2016-01-04T12:00:00Z   0.0    -6.875    113.125  30.35
4  2016-01-05T12:00:00Z   0.0    -6.875    113.125  30.60

## 4. Bersihkan & rapikan data

- Ubah kolom `time` menjadi format datetime
- Urutkan berdasarkan waktu
- Hilangkan duplikat (jika ada)

In [4]:
# 4. Bersihkan & rapikan data
df["time"] = pd.to_datetime(df["time"])
df = df.rename(columns={"time": "datetime"})

df = df.sort_values("datetime").drop_duplicates().reset_index(drop=True)

print("Rentang waktu data:", df["datetime"].min(), "sampai", df["datetime"].max())
print("Jumlah baris akhir:", len(df))
df.head()

Rentang waktu data: 2016-01-01 12:00:00+00:00 sampai 2025-12-31 12:00:00+00:00
Jumlah baris akhir: 3647

                   datetime  zlev  latitude  longitude    sst
0 2016-01-01 12:00:00+00:00   0.0    -6.875    113.125  30.23
1 2016-01-02 12:00:00+00:00   0.0    -6.875    113.125  30.01
2 2016-01-03 12:00:00+00:00   0.0    -6.875    113.125  30.02
3 2016-01-04 12:00:00+00:00   0.0    -6.875    113.125  30.35
4 2016-01-05 12:00:00+00:00   0.0    -6.875    113.125  30.60

## 5. Export ke CSV

Simpan seluruh data yang sudah digabung ke dalam satu file CSV utuh.

In [5]:
# 5. Simpan ke file CSV
output_path = "sst_pasuruan_2016-2025_merged.csv"
df.to_csv(output_path, index=False)

print(f"Berhasil disimpan: {output_path}")
print(f"Total baris: {len(df):,}")
print(f"Total kolom: {len(df.columns)}")

Berhasil disimpan: sst_pasuruan_2016-2025_merged.csv
Total baris: 3,647
Total kolom: 5

In [6]:
# Cek ulang hasil file CSV
check = pd.read_csv(output_path)
check.info()
check.head()

<class 'pandas.DataFrame'>
RangeIndex: 3647 entries, 0 to 3646
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   datetime   3647 non-null   str
 1   zlev       3647 non-null   float64
 2   latitude   3647 non-null   float64
 3   longitude  3647 non-null   float64
 4   sst        3647 non-null   float64
dtypes: float64(4), str(1)
memory usage: 142.6 KB

                    datetime  zlev  latitude  longitude    sst
0  2016-01-01 12:00:00+00:00   0.0    -6.875    113.125  30.23
1  2016-01-02 12:00:00+00:00   0.0    -6.875    113.125  30.01
2  2016-01-03 12:00:00+00:00   0.0    -6.875    113.125  30.02
3  2016-01-04 12:00:00+00:00   0.0    -6.875    113.125  30.35
4  2016-01-05 12:00:00+00:00   0.0    -6.875    113.125  30.60